#!/bin/bash
#
# Copyright 2017 IBM Corp. All Rights Reserved
#
# Licensed under the Apache License, Version 2.0 (the License);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an AS IS BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script creates an Object Storage Bridge.

showenv()
{
	echo OS_AUTH_URL=${OS_AUTH_URL}
	echo OS_REGION=${OS_REGION}
	echo OS_PASSWORD=${OS_PASSWORD}
	echo OS_PROJECT_ID=${OS_PROJECT_ID}
	echo OS_USER_ID=${OS_USER_ID}
	echo MH_API_KEY=${MH_API_KEY}
}

if [ -z "${OS_AUTH_URL}" -o -z "${OS_REGION}" -o -z "${OS_PASSWORD}" -o -z "${OS_PROJECT_ID}" -o -z "${OS_USER_ID}" -o -z "${MH_API_KEY}" ];
then
	echo Required environment variables missing
	showenv
	exit 1
fi

echo {\
    \"name\":\"osbridge\",\
    \"topic\":\"carevents\",\
    \"type\":\"objectStorageOut\",\
    \"configuration\":{\
        \"credentials\":{\
            \"authUrl\":\"${OS_AUTH_URL}\",\
            \"region\":\"${OS_REGION}\",\
            \"password\":\"${OS_PASSWORD}\",\
            \"projectId\":\"${OS_PROJECT_ID}\",\
            \"userId\":\"${OS_USER_ID}\"\
        },\
        \"container\":\"carevents\",\
        \"uploadDurationThresholdSeconds\":600,\
        \"uploadSizeThresholdKB\":1024,\
        \"inputFormat\":\"json\",\
        \"partitioning\":[\
            {\
                \"type\":\"dateIso8601\",\
                \"propertyName\":\"ts\"\
            }\
        ]\
    }\
} |
curl -H 'Content-Type: application/json' -H 'Accept: */*' -H X-Auth-Token:\ ${MH_API_KEY} https://kafka-admin-prod01.messagehub.services.us-south.bluemix.net:443/admin/bridges -d @-
