#!/bin/bash
#
# Copyright 2017 IBM Corp. All Rights Reserved
#
# Licensed under the Apache License, Version 2.0 (the License);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an AS IS BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This scripts lists the Message Hub bridges.

showenv()
{
	echo MH_API_KEY=${MH_API_KEY}
}

if [ -z "${MH_API_KEY}" ];
then
	echo Required environment variables missing
	showenv
	exit 1
fi

echo Message Hub bridges
curl -H 'Content-Type: application/json' -H 'Accept: */*' -H X-Auth-Token:\ ${MH_API_KEY} https://kafka-admin-prod01.messagehub.services.us-south.bluemix.net:443/admin/bridges
echo
