#!/bin/bash
#
# Copyright 2017 IBM Corp. All Rights Reserved
#
# Licensed under the Apache License, Version 2.0 (the License);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an AS IS BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script uploads the Kafka 0.10.2 client JAR to the Spark service.

showenv()
{
	echo SPARK_TENANT_ID=${SPARK_TENANT_ID}
	echo SPARK_TENANT_SECRET=${SPARK_TENANT_SECRET}
	echo SPARK_INSTANCE_ID=${SPARK_INSTANCE_ID}
}

if [ -z "${SPARK_TENANT_ID}" -o -z "${SPARK_TENANT_SECRET}" -o -z "${SPARK_INSTANCE_ID}" ];
then
	echo Required environment variables missing
	showenv
	exit 1
fi

curl -X PUT -k -u ${SPARK_TENANT_ID}:${SPARK_TENANT_SECRET} -H X-Spark-service-instance-id:\ ${SPARK_INSTANCE_ID} --data-binary @"/home/demo/lib/kafka-clients-0.10.2.0.jar" https://spark.bluemix.net/tenant/data/libs/kafka-clients-0.10.2.0.jar
